import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Montserrat } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/providers/theme-provider";

import "./globals.css";
import AppSidebar from "@/components/side-bar/app-sidebar";

const montserrat = Montserrat({
  style: ["italic", "normal"],
  subsets: ["latin-ext"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
  adjustFontFallback: true,
  fallback: ["Helvetica Neue", "sans-serif"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <main className="w-full h-full">
              <SidebarTrigger className="cursor-pointer ms-1 mt-1" />
              <section className="p-2 container mx-auto">{children}</section>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
